# The URL the site will be built for
base_url = "https://touhoufest.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]

[extra]
site_name = "TouhouFest"

[extra.socials]
discord_invite = "https://discord.touhoufest.org"
twitter = "https://twitter.com/TouhouFest"
bluesky = "https://bsky.app/profile/touhoufest.org"
youtube = "https://www.youtube.com/@touhoufestofficial"
instagram = "http://www.instagram.com/touhoufest"
