# On every push this script is executed
on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Rebuild at 12 Midnight every day
  schedule:
    - cron: "0 0 * * *"

name: Build site
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Install zola
        uses: taiki-e/install-action@v2.87.15
        with:
          tool: zola@0.23.6
      - name: Build site
        run: zola build
